# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
   include:
     - dev
  paths:
    include:
      - helm

#pool: Default
pool:
  vmImage: ubuntu-20.04
steps:
- script: |
    echo "Hello"
    pwd
    ls -la

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/helm'
    includeRootFolder: false
    archiveType: 'zip'
#    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/helm.zip'
    replaceExistingArchive: true
- task: PublishPipelineArtifact@1
  inputs:
#    targetPath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    targetPath: '$(Build.SourcesDirectory)/helm'
#    targetPath: '$(Build.ArtifactStagingDirectory)/helm.zip'
    artifact: 'helm.zip'
    publishLocation: 'pipeline'