version: '2'

services:
    fe:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    be:
        image: nginx:latest
        ports:
            - "8081:80"
        volumes:
            - ./code:/code
            - ./siteback.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        build: ./php/
#        image: php:fpm
#        ports:
#            - 9000:9000
        volumes:
            - ./code:/code
        networks:
            - code-network
    db:
        image: mariadb
        networks:
            - code-network
        environment:
            - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
networks:
    code-network:
      driver: bridge
