trigger:
  batch: true
  branches:
   include:
     - dev
  paths:
    include:
      - front-end

pool: Default
#  vmImage: ubuntu-20.04

variables:
- name: testpath
  value: front-end

steps:



- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'sonar'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'nhl'
    cliSources: '.'
- script: |
    echo "$SONARQUBE_SCANNER_PARAMS"
    params=`echo "$SONARQUBE_SCANNER_PARAMS" | sed 's/"sonar.branch.name":"[-a-z0-9/]*",//ig'`
    echo "$params"
    echo "##vso[task.setvariable variable=SONARQUBE_SCANNER_PARAMS]$params"
    echo "$SONARQUBE_SCANNER_PARAMS"
  displayName: Define SONARQUBE_SCANNER_PARAMS variable
- task: SonarQubeAnalyze@4
- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'
