trigger:
  batch: true
  branches:
   include:
     - dev
  paths:
    include:
      - front-end

pool: Default
#  vmImage: ubuntu-20.04

variables:
- name: testpath
  value: front-end

steps:



- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'sonar'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'nhl'
    cliSources: '.'
- powershell: |
    $params = "$env:SONARQUBE_SCANNER_PARAMS" -replace '"sonar.branch.name":"[\w,/,-]*"\,?'
    Write-Host "##vso[task.setvariable variable=SONARQUBE_SCANNER_PARAMS]$params"

- task: SonarQubeAnalyze@4
- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'
