trigger:
  batch: true
  branches:
   include:
     - dev
  paths:
    include:
      - front-end

pool: #Default
  vmImage: ubuntu-20.04

variables:
- name: testpath
  value: front-end

steps:



- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'sonar'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'nhl'
    cliSources: '.'
    extraProperties: |
      sonar.branch.name=
- task: SonarQubeAnalyze@4
- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'
