apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonar
  template:
    metadata:
      labels:
        app: sonar
    spec:
      containers:
      - name: sonar
        image: sonarcube
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
        - name: AZP_URL
          value: https://dev.azure.com/vujo3
        - name: AZP_AGENT_NAME
          value: "k8sagent-{{ . }}"
        - name: AZP_TOKEN
          value: {{ $.Values.azp_token }}
#        ports:
#        - containerPort: 80


