---
kind: Service
apiVersion: v1
metadata:
  name: sonar
spec:
  ports:
    - protocol: TCP
      port: 9000

---
apiVersion: v1
kind: Endpoints
metadata:
  name: sonar
subsets:
  - addresses:
      - ip: {{ .Values.sonar_ip }}
    ports:
      - port: 9000

