trigger:
  batch: true
  branches:
   include:
     - dev
  paths:
    include:
      - front-end

#pool: Default
pool:
  vmImage: ubuntu-20.04
steps:

# - script: VERSION_TAG=`git tag --sort=-creatordate` && echo "##vso[task.setvariable variable=VERSION_TAG]$VERSION_TAG"
- script: VERSION_TAG=`git describe --tags` && echo "##vso[task.setvariable variable=VERSION_TAG]$VERSION_TAG"
  displayName: Define VERSION_TAG variable

- task: Docker@2
  inputs:
    containerRegistry: 'acr'
    repository: 'nhl_fe_dev'
    command: 'buildAndPush'
    Dockerfile: 'front-end/Dockerfile'
    tags: $(VERSION_TAG)

