#CREATE DATABASE nhl;
#USE nhl;
CREATE TABLE IF NOT EXISTS players (id INT PRIMARY KEY AUTO_INCREMENT, player_id INT UNIQUE KEY, fullname VARCHAR(300), birthCountry VARCHAR(10));
CREATE TABLE IF NOT EXISTS goals (id INT PRIMARY KEY AUTO_INCREMENT, game_id INT, player_id INT, goals INT, venue VARCHAR(200),
	CONSTRAINT game_player_uk  UNIQUE (game_id,player_id)
	);
CREATE TABLE IF NOT EXISTS venues (id INT PRIMARY KEY AUTO_INCREMENT, venue_id INT, city VARCHAR(200), name VARCHAR(200), country VARCHAR(50));

INSERT IGNORE INTO `venues` VALUES (1,5046,'Anaheim','Honda Center','United States'),(2,5085,'Boston','TD Garden','United States'),(3,5039,'Buffalo','KeyBank Center','United States'),(4,5075,'Calgary','Scotiabank Saddledome','Canada'),(5,5092,'Chicago','United Center','United States'),(6,5059,'Columbus','Nationwide Arena','United States'),(7,5019,'Dallas','American Airlines Center','United States'),(8,5064,'Denver','Ball Arena','United States'),(9,5145,'Detroit','Little Caesars Arena','United States'),(10,5100,'Edmonton','Rogers Place','Canada'),(12,5043,'Glendale','Gila River Arena','United States'),(13,5178,'Las Vegas','T-Mobile Arena','United States'),(14,5081,'Los Angeles','STAPLES Center','United States'),(16,5030,'Nashville','Bridgestone Arena','United States'),(17,5054,'New York','Madison Square Garden','United States'),(18,0,'Newark','Prudential Center','United States'),(19,5031,'Ottawa','Canadian Tire Centre','Canada'),(20,5096,'Philadelphia','Wells Fargo Center','United States'),(21,5034,'Pittsburgh','PPG Paints Arena','United States'),(22,5066,'Raleigh','PNC Arena','United States'),(23,0,'San Jose','SAP Center at San Jose','United States'),(25,5076,'St. Louis','Enterprise Center','Canada'),(26,5098,'St. Paul','Xcel Energy Center','Canada'),(27,5027,'Sunrise','BB&T Center','United States'),(29,0,'Toronto','Scotiabank Arena','Canada'),(30,5073,'Vancouver','Rogers Arena','Canada'),(31,5094,'Washington','Capital One Arena','United States'),(32,0,'Winnipeg','Bell MTS Place','Canada'),(33,0,'Stateline','Edgewood Tahoe Resort','United States'),(34,5017,'Tampa','Amalie Arena','United States'),(35,5028,'Montreal','Centre Bell','Canada'),(36,0,'Uniondale','Nassau Veterans Memorial Coliseum','United States');
