apiVersion: apps/v1
kind: Deployment
metadata:
  name: azagent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azagent
  template:
    metadata:
      labels:
        app: azagent
    spec:
      containers:
{{- range .Values.containers }}
      - name: azureagent-{{ . }}
        image: {{ $.Values.image }}
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
        - name: AZP_URL
          value: https://dev.azure.com/vujo3
        - name: AZP_AGENT_NAME
          value: "k8sagent-{{ . }}"
        - name: AZP_TOKEN
          value: {{ $.Values.azp_token }}
#        ports:
#        - containerPort: 80
{{- end }}    

---

# AZP_URL=https://dev.azure.com/vujo3 -e AZP_TOKEN=$1 -e AZP_AGENT_NAME=mydockeragent cywl/azureagent:latest
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: azagent
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: azagent
