trigger:
  batch: true
  branches:
   include:
     - dev
  paths:
    include:
      - back-end

#pool: Default
pool:
  vmImage: ubuntu-20.04

variables:
- name: testpath
  value: back-end

steps:

#- script: VERSION_TAG=`git tag --sort=-creatordate` && echo "##vso[task.setvariable variable=VERSION_TAG]$VERSION_TAG"
- script: VERSION_TAG=`git describe --tags` && echo "##vso[task.setvariable variable=VERSION_TAG]$VERSION_TAG"
  displayName: Define VERSION_TAG variable

- script: |
    res=0
    for file in $( find ${{ variables.testpath }} -type f -name '*.php' ); do
      php -l "$file" || res=1
    done
    if [ $res != 0 ]; then echo "##vso[task.logissue type=error]PHP syntax error."
    else
      echo "$VERSION_TAG">version_tag
    fi
    exit $res
  displayName: Lint PHP files

- task: Docker@2
  inputs:
    containerRegistry: 'acr'
    repository: 'nhl_be_dev'
    command: 'buildAndPush'
    Dockerfile: 'back-end/Dockerfile'
    tags: $(VERSION_TAG)

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'version_tag'
    artifact: 'version_tag'
    publishLocation: 'pipeline'
