apiVersion: v1
kind: ConfigMap
metadata:
  name: appconfig
data:
  appconfig: |
    # first line comment
    <?php
    $db_host = "{{ .Values.db.host }}";
    $db_name = "{{ .Values.db.name }}";
    $db_user = "{{ .Values.db.user }}";
    $db_pass = "{{ .Values.db.pass }}";
    $adminpass = "{{ .Values.adminpass }}";
    ?>
