---
- name: Prepare control node
  hosts: [all]
  tasks:
  - name: Enable swap
    lineinfile:
      path: /etc/waagent.conf
      regexp: '^ResourceDisk.EnableSwap='
      line: ResourceDisk.EnableSwap=y
    register: sw_en
  - name: Set swap size
    lineinfile:
      path: /etc/waagent.conf
      regexp: '^ResourceDisk.SwapSizeMB='
      line: ResourceDisk.SwapSizeMB=2048
    register: sw_size
  - name: Restart agent
    service:
      name: waagent
      state: restarted
    when: sw_en.changed or sw_size.changed

  - name: Install epel
    yum:
      name: [ epel-release, yum-utils ]
      state: latest
  - name: Add hashicorp repository
    shell: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    args:
      creates: /etc/yum.repos.d/hashicorp.repo
  - name: Add docker-ce repository
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
  - name: Add kubectl repository
    yum_repository:
      name: Kubernetes
      description: Google k8s repo
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      repo_gpgcheck: yes
      gpgcheck: yes
      gpgkey:
        - https://packages.cloud.google.com/yum/doc/yum-key.gpg
        - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  - name: Install packages
    yum:
      name: [ ansible, terraform, docker-ce, docker-ce-cli, containerd.io, python-docker-py, docker-compose, kubectl, git] # 
      state: latest
#  - name: Download docker-compose
#    shell: |
#      curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
#      chmod +x /usr/local/bin/docker-compose
#    args:
#      creates:
#        /usr/local/bin/docker-compose

#  - name: Create dir for infrastructure
#    file:
#      path: /root/school/infrastructure
#      state: directory
#      mode: '770'
  - name: Start docker
    service:
      name: docker
      state: started
      enabled: yes
  - name: Download last infrastructure config
    unarchive:
      src: https://github.com/Qutianer/dev-sch/releases/latest/download/infrastructure.tar.gz
      dest: /root
      remote_src: yes
  - name: Copy credentials for terraform
    copy:
      src: ./creds
      dest: /root
  - name: Create dir for ssh
    file:
      path: /root/.ssh/
      state: directory
      mode: '700'
  - name: Generate ssh keys
    openssh_keypair:
      path: /root/.ssh/id_rsa
  - sysctl:
      name: vm.max_map_count
      value: 262144
#  - name: Run docker-compose up again
#    docker_compose:
#      project_src: sonar
  - name: Run docker-compose up again
    shell: |
      cd /root/sonar
      docker-compose up -d

