- name: Prepare control node
  hosts: [all]
  vars_files:
    - sp.auto.tfvars
  tasks:
  - name: Log into private registry and force re-authorization
    docker_login:
      registry: "{{ acr_url }}"
      username: "{{ client_id }}"
      password: "{{ client_secret }}"

