---
- name: Prepare infrastructure
  hosts: localhost
  connection: local
  vars:
    containers: [ nginx ]
  vars_files:
    - secrets.cred
  tasks:
  - name: Install docker module for ansible
    yum:
      name: python-docker-py
      state: latest
  - name: Log into private registry and force re-authorization
    docker_login:
      registry: "{{ acr_url }}"
      username: "{{ client_id }}"
      password: "{{ client_secret }}"
  - name: Pull nginx
    docker_image:
      name: "{{ item }}"
      source: pull
    with_items: "{{containers}}"
  - name: Tag and push to private repo
    docker_image:
      name: "{{ item }}"
      repository: "{{ acr_url }}/{{ item | basename }}-my"
      push: yes
      source: local
    with_items: "{{containers}}"

