name: Build and push azure pipeline agent
on:
  push:
    path:
      - 'cicd'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: cicd
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/azureagent:latest
