name: Create release with archives
on:
  push:
    paths:
      - 'iac/version'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
#    - name: Archive Release
#      uses: thedoctor0/zip-release@master
#      with:
#        type: 'tar'
#        filename: 'release.tar.gz'
#        exclusions: '*.git*'
    - name: Archive release
      run: |
        #        pushd control
        #        tar -caf ../control.tar.gz --exclude-vcs --exclude-vcs-ignores *
        #        popd
        pushd iac
        tar -caf ../infrastructure.tar.gz --exclude-vcs --exclude-vcs-ignores *
        popd
        tag=`cat iac/version`
        echo $tag
        echo "::set-env name=tag::$tag"
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: |
          infrastructure.tar.gz
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "infrastructure.tar.gz"
        tag: $tag
        token: ${{ secrets.GITHUB_TOKEN }}
